name: unpleasantville
favicon: null
layout_spectrum: 0.8462599071208388
typography_spectrum: 0.16601
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
